#!/bin/bash

PASSWORD_SIZE_IN_BYTES=20
LETTERS_UPR='ABCDEFGHIJKLMNOPQRSTUVWXYZ'
LETTERS_LWR='abcdefghijklmnopqrstuvwxyz'
LETTERS_BOTH=${LETTERS_UPR}${LETTERS_LWR}
NUMBERS='1234567890'
SPECIALS='!@#$%^&*()_+=[]{}<>/?'

echo "----Password Size in Bytes----"
echo $PASSWORD_SIZE_IN_BYTES

echo
echo "----Numbers and Letters----"
for i in $(echo {1..10}); do
  cat /dev/urandom | tr -cd ${LETTERS_BOTH}${NUMBERS} | head --bytes=${PASSWORD_SIZE_IN_BYTES}
  echo
done

echo
echo "----Numbers, Letters and Specials----"
for i in $(echo {1..10}); do
  cat /dev/urandom | tr -cd ${LETTERS_BOTH}${NUMBERS}${SPECIALS} | head --bytes=${PASSWORD_SIZE_IN_BYTES}
  echo
done
echo